# Generated by Django 5.2.6 on 2025-10-14 03:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField(default=0, help_text='Edad aproximada en años')),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('genero', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('adoptado', 'Adoptado'), ('en_proceso', 'En proceso de adopción')], default='disponible', max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('vacunado', models.BooleanField(default=False)),
                ('esterilizado', models.BooleanField(default=False)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('motivo_general', models.TextField()),
                ('motivo_especifico', models.TextField()),
                ('otros_animales', models.TextField(blank=True, null=True)),
                ('historial_animales', models.TextField(blank=True, null=True)),
                ('acuerdo_familia', models.BooleanField(default=False)),
                ('hay_ninios', models.BooleanField(default=False)),
                ('edades_ninios', models.CharField(blank=True, max_length=100, null=True)),
                ('alergias', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_vivienda', models.CharField(blank=True, max_length=50, null=True)),
                ('se_permiten_animales', models.BooleanField(default=False)),
                ('espacio_suficiente', models.BooleanField(default=False)),
                ('que_pasa_si_muda', models.TextField(blank=True, null=True)),
                ('cambios_trato', models.TextField(blank=True, null=True)),
                ('situacion_empleo', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_gastos', models.CharField(blank=True, max_length=100, null=True)),
                ('puede_cubrir_gastos', models.BooleanField(default=False)),
                ('cuidados', models.TextField(blank=True, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('comentarios_extra', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mascota')),
            ],
        ),
    ]
