# Generated by Django 5.2.6 on 2025-10-10 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('motivo_general', models.TextField()),
                ('motivo_especifico', models.TextField()),
                ('otros_animales', models.TextField(blank=True, null=True)),
                ('historial_animales', models.TextField(blank=True, null=True)),
                ('acuerdo_familia', models.BooleanField(default=False)),
                ('hay_ninios', models.BooleanField(default=False)),
                ('edades_ninios', models.CharField(blank=True, max_length=100, null=True)),
                ('alergias', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_vivienda', models.CharField(blank=True, max_length=50, null=True)),
                ('se_permiten_animales', models.BooleanField(default=False)),
                ('espacio_suficiente', models.BooleanField(default=False)),
                ('que_pasa_si_muda', models.TextField(blank=True, null=True)),
                ('cambios_trato', models.TextField(blank=True, null=True)),
                ('situacion_empleo', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_gastos', models.CharField(blank=True, max_length=100, null=True)),
                ('puede_cubrir_gastos', models.BooleanField(default=False)),
                ('cuidados', models.TextField(blank=True, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('comentarios_extra', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mascota')),
            ],
        ),
    ]
