# Generated by Django 5.2.6 on 2025-10-26 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudadopcion',
            old_name='historial_animales',
            new_name='animales_anteriores',
        ),
        migrations.RenameField(
            model_name='solicitudadopcion',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='solicitudadopcion',
            old_name='acuerdo_familia',
            new_name='familia_de_acuerdo',
        ),
        migrations.RemoveField(
            model_name='solicitudadopcion',
            name='cambios_trato',
        ),
        migrations.RemoveField(
            model_name='solicitudadopcion',
            name='cuidados',
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_mensaje',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='Tiempo_juego_afecto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='donde_duerme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='ninios_convivencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='paseo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='paseos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='persona_ideal',
            field=models.TextField(default='sin especificar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='plato_limpio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='que_pasa_si_enferma',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='que_paso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='tiempo_solo_dia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='tiene_veterinario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='vacunacion_desparasitacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='veterinario',
            field=models.BooleanField(default=False),
        ),
    ]
