# Generated by Django 5.2.6 on 2025-10-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_historial_animales_solicitudadopcion_animales_anteriores_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Mensaje',
        ),
    ]
