# Generated by Django 5.2.6 on 2025-10-30 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_contacto_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('refugio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(help_text='Calle, número, colonia, etc.', max_length=200)),
                ('estado', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('capacidad', models.PositiveIntegerField(default=0, help_text='Número máximo de animales que puede albergar')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='refugio',
            field=models.ForeignKey(blank=True, help_text='Refugio donde se encuentra la mascota.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='core.refugio'),
        ),
    ]
